### ISSUE TITLE
As a user I want to view the list of events on the Home page within my favorite categories 

### ISSUE THREAD

**Issue by mehalyna** [EventsExpress-SoftServe/EventsExpress#100]
1. As a user I have the ability to choose my favorite categories while editing the profile.
2. Use this feature to filter the list of categories on my Home page.
3. In the case of an empty list, use some default criteria (most popular, not far in the future, etc).

**Comment by andrii-zaharovskyi** [comment]
- [x] Create events filter into the global state.
- [x] Change current interaction logic with the events filter.
- [x] Update the base routes and the react-router-dom library.
- [x] Implement saving the state of the event filter in the event filter form after reloading the event page.
