### ISSUE TITLE
The 'Events Express' button does not transfer the user to the landing page

### ISSUE THREAD

**Issue by olenahnatyuk** [EventsExpress-SoftServe/EventsExpress#1231]
**Date Time**
04/10/2022

**Priority**
High

**Environment:**
OS Windows 10
Browser Chrome
Version 100.0.4896.75 (Official Build) (64-bit)
Reproducible: always.

**Pre-conditions:**
1. Go to https://eventsexpress-test.azurewebsites.net/landing.
2. Log in as a User5 in the user table.

**Steps to Reproduce**
1. Click on the 'Create Event' button in the top right corner.
2. Click on the 'Events Express' button in the top left corner.

**Expected result**
After clicking the 'Event Express' button the user should be transferred to the landing page.

**Actual result**
After clicking the 'Event Express' button the user is not transferred to the landing page.

User story #962 Test case #1129

**Comment by mehalyna** [comment]
Not a bug
