### ISSUE TITLE
Verify if Unregistered User Is  able to choose type of activities on registration questionnaire page 

### ISSUE THREAD

**Issue by ArthurDudko** [EventsExpress-SoftServe/EventsExpress#1266]
**Date Time**
06-15-2022 18:00

**Priority**
 Medium 

**Description**
Verify if after  User open "Step 3" on registration page the next groups of activities are shown:
Arts & Craft,
Education&Training,
Health&Wellness&Fitness.

After user choose any one  the system opens modal window with the list of hobbies (as checkbox) list.
User are able to choose the  hobbies (on checkbox) list.
After User choose activities, select hobbies and press "CONTINUE"  page should redirect him to page "4"
All selected hobbies and activities

**Pre-requisites**
The authorization is implemented

**Steps to be fulfilled before test:**
1.  Move to Registration page
2. Start Login registration
3. Go to "Step 3" page(groups of activities).

**Test Cases**
|      S#     |    Action   |  Test Data  | Expected Result | Actual Result |     P/F     |  Automated  |
|:-----------:|:-----------:|:-----------:|:---------------:|:-------------:|:-----------:|:-----------:|
|    1     |    Go to "Page 3(groups of activities)"    |        | After Choosing  "Arts & Craft" activities, the system should open modal window with the list of hobbies (as checkbox)       |     Modal window as a Checkbox are opened      |    P    |    <br>     |
|    3     |    Choose "Dancing" hobbie from checkbox      |       |      The list of selected hobbie should be visible       |     The list of selected hobbie are  visible      |    P    |    <br>     |
|    4     |    Press "Continue" buttton      |    <br>     |      User must be redirected to page "4" selected hobbies and activities should be saved      |     User are redirected to page "4"      |    P     |    <br>     |

**Environment:**
 - OS: MAC OS MONTEREY 12.2.1
 - Browser SAFARY
 - Version 15.3
  User story links E.g.: "User story #859 "

Labels to be added "Test case", Priority ("pri: "), Type ("UI, "Functional"), "API" .

**Comment by arthur19967** [comment]
1
