### ISSUE TITLE
An admin can create duplicate of an existing category (if non-printable spaces are used)

### ISSUE THREAD

**Issue by mehalyna** [EventsExpress-SoftServe/EventsExpress#163]
**Date Time**
11-17-2020 15:30

**Priority**
Medium

**Description**
An admin can create a duplicate of an existing category in the case of using non-printable spaces in its name.

**Pre-conditions**
Login into EventExpress as an admin 

**Steps to Reproduce**
1. Select Categories
2. Add a new category (by pressing Plus on the top of the screen)
3. Type Summer and then add space (press space bar) before Summer.
4. New Category is created which visually looks the same as already existing (both at the front-end and in the database). 

**Expected result**
The system should check for similarity and suggest if a similar event is already created. 

**Actual result**
An event visually looking similar to an existing one is created. 

**Environment:**
Windows 10 Home OS Build 18363.1139
Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Additional context**

**Comment by vladspirin** [comment]
Confirmation test: pass
Status: 'Verified​'
Test case: [#362 Verify that an admin cannot create a duplicate of an existing category (if non-printable spaces are used)](https://github.com/ita-social-projects/EventsExpress/issues/362) 

![Screenshot_81](https://user-images.githubusercontent.com/24988700/103082562-0d6be680-45e3-11eb-9a17-72067982e4bd.png)
