### ISSUE TITLE
Spelling mistakes in notification messages after receiving a new message in Comuna.

### ISSUE THREAD

**Issue by OleksandraReveha** [EventsExpress-SoftServe/EventsExpress#245]
**Date Time**
11.28.2020 20:42

**Priority**
 Low

**Description**
When an authorized user gets a new message, he can view 'You have 1 unread messages' instead of 'You have 1 unread message'. On the left bottom of the page, a user can view a notification 'You have new message' instead of 'You have a new message'. 

**Pre-conditions**
Steps to be fulfilled before reproduction:
Go to https://eventsexpress-test.azurewebsites.net/
Login as a user/admin

**Steps to Reproduce**
1. Go to 'Comuna'
2. See two errors after receiving a new message.

**Expected result**
 'You have 1 unread messa**ge**'. 
On the left bottom of the page, a user can view 'You have **a** new message'. 

**Actual result**
 'You have 1 unread messages' 
 On the left bottom of the page, a user can view a notification 'You have new message'.

**Screenshots**
![Screenshot_87](https://user-images.githubusercontent.com/74773706/100523810-5f784280-31c4-11eb-9fef-e384cb04d0e0.png)

**Environment:**
- OS: [Windows 10 Pro 2004 20H1 19041.630]
 - Browser [Google Chrome 86.0.4240.198 ]

**Additional context**

**Comment by vladspirin** [comment]
Confirmation test: pass
Test case: [#243 Verify that an authorized user can chat in Comuna](https://github.com/ita-social-projects/EventsExpress/issues/243)
