### ISSUE TITLE
The pagination component doesn't work on the 'Event' page

### ISSUE THREAD

**Issue by ElenaMelnyk** [EventsExpress-SoftServe/EventsExpress#251]
**Date Time**
28-11-2020 23:37

**Priority**
High 

**Description**
The pagination component under the events list in the middle of the page is used to navigate through the pages of the events list. All its elements doesn't navigate through the events list.

**Pre-conditions**
Steps to be fulfilled before test:
Move to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
Authorize as admin privileges
Open the “Events” page

**Steps to Reproduce**
1. Click on the '2' button

**Expected result**
Page number 2 is Opened with information about events. The 'Last', 'Backward' and the 'Forward' buttons are enabled.

**Actual result**
A white page appears with no elements

**Screenshots**
![bug_2](https://user-images.githubusercontent.com/74773749/100526612-39a66a00-31d3-11eb-8f20-cfb2290bc4ec.jpg)

**Environment:**
 windows 10 corporate (64 bit)
Google Chrome
87.0.4280.66 (64 bit)

**Additional context**
Test https://github.com/EventsExpress-SoftServe/EventsExpress/issues/250

**Comment by Anastasiagumenuk9** [comment]
This page has been deleted

**Comment by ElenaMelnyk** [comment]
@Anastasiagumenuk9 
Pass
