### ISSUE TITLE
The filter 'block' doesn't filter the events on the 'Event'/'Home' page

### ISSUE THREAD

**Issue by ElenaMelnyk** [EventsExpress-SoftServe/EventsExpress#267]
**Date Time**
29-11-2020 16:36

**Priority**
High

**Description**
By the requirements when the radio button "Blocked" is selected only events that have been blocked and marked in yellow are displayed.
When the radio button "Blocked" is selected in the filter on the 'Home'/'Event/ page the error message is displayed.

**Pre-conditions**
Steps to be fulfilled before test:
Move to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
Login like an admin user

**Steps to Reproduce**
1. Select the "Blocked" button and click on the 'Serch' button

**Expected result**
Only events that have been blocked and marked in yellow are displayed

**Actual result**
 the error message appears '403!-Forbidden'

**Screenshots**
![bug_3_block](https://user-images.githubusercontent.com/74773749/100544951-e3343c80-3261-11eb-8901-e005c63426fd.jpg)

**Environment:**
windows 10 corporate (64 bit)
Google Chrome
87.0.4280.66 (64 bit)

**Additional context**
Test https://github.com/EventsExpress-SoftServe/EventsExpress/issues/264

**Comment by Anastasiagumenuk9** [comment]
@ElenaMelnyk , I couldn't reproduce this one. Could you check one more time is it still occurce for you?
