### ISSUE TITLE
The filter 'All' doesn't filter the events on the 'Event'/'Home' page

### ISSUE THREAD

**Issue by ElenaMelnyk** [EventsExpress-SoftServe/EventsExpress#268]
**Date Time**
11-29-2020 16:45

**Priority**
High

**Description**
By the requirements when the radio button "All" is selected, all the events in the system are displayed.
When the radio button "All" is selected in the filter on the 'Home'/'Event/ page the error message is displayed.

**Pre-conditions**
Steps to be fulfilled before the test:
Move to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
Login like an admin user

**Steps to Reproduce**
1. Select the "All" button and click on the 'Search' button.

**Expected result**
all the events in the system are displayed

**Actual result**
 the error message appears '403!-Forbidden'

**Screenshots**
![bug_4_all](https://user-images.githubusercontent.com/74773749/100545040-70779100-3262-11eb-8348-7dec507f6037.jpg)

**Environment:**
windows 10 corporate (64 bit)
Google Chrome
87.0.4280.66 (64 bit)

**Additional context**
Test https://github.com/EventsExpress-SoftServe/EventsExpress/issues/264

**Comment by Anastasiagumenuk9** [comment]
@vladspirin  , I couldn't reproduce this one. Could you check one more time is it still occurce for you?

**Comment by ElenaMelnyk** [comment]
@Anastasiagumenuk9 the error is not reproducible at the moment
