### ISSUE TITLE
A new event is not created on the profile page.

### ISSUE THREAD

**Issue by ElenaMelnyk** [EventsExpress-SoftServe/EventsExpress#283]
**Date Time**
07-12-2020 22:36
 **Tags**
20201207.8

**Priority**
High 

**Description**
A new event on the 'Profile' page does not create after clicking the 'Save' button

**Pre-conditions**
1. Go to https://eventsexpress-test.azurewebsites.net/user/1a816f69-521f-4876-cd1d-08d8831eb70c
2. log in as an admin
3. The 'Profile' page is opened

**Steps to Reproduce**

1. Click on the 'Add event' button
2.  Input the values: 
'Title'='Будуємо успішно своє майбутнє' 
'Description'='Test'
“#hashtags”='fun'
'Country'='Ukraine' 
'City'='Chernivtsi'
3. Click on the 'Save' button

**Expected result**
The event creation form closed and the message appears "events successfully created"

**Actual result**
The event creation form remained open with all the data that we entered

**Screenshots**
![createEvent](https://user-images.githubusercontent.com/74773749/101401751-6f3a0a00-38db-11eb-9f43-7ce68de6fc70.jpg)

**Environment:**
windows 10 corporate (64 bit)
Google Chrome
87.0.4280.66 (64 bit)

**Additional context**
https://github.com/EventsExpress-SoftServe/EventsExpress/issues/280

**Comment by vladspirin** [comment]
The image must be added to the drag-and-drop image upload field. Required.

**Comment by vladspirin** [comment]
Not an issue

**Comment by ElenaMelnyk** [comment]
@vladspirin 
when the event, in principle, is not formed this is a bug :-)

**Comment by ElenaMelnyk** [comment]
Pass
