### ISSUE TITLE
The 'Cancel' button is not implemented on the new form of the event on the 'Profile' page. 

### ISSUE THREAD

**Issue by ElenaMelnyk** [EventsExpress-SoftServe/EventsExpress#284]
**Date Time**
12-07-2020  23:39

 **Tags**
20201207.8

**Priority**
High

**Description**
The 'Cancel' button is not implemented on the new form of the event on the 'Profile' page in the middle of the bottom edge of the form of the new event. 

**Pre-conditions**
1. Move to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
2. Login as an admin: "login"='noneivaAdm@gmail.com ' , "password"= 'QWERTY123.'
3. The 'Profile' page is opened

**Steps to Reproduce**
1.  Click on the 'Add event' button
2.  Click on the 'Cancel' button

**Expected result**
The forms is closed, the new event does not create, the 'Profile' page remains open

**Actual result**
The 'Cancel' button is not implemented on the new form of the event

**Screenshots**
![bug_5](https://user-images.githubusercontent.com/74773749/101410011-64857200-38e7-11eb-92b9-31386b215d9e.jpg)

**Environment:**
windows 10 corporate (64 bit)
Google Chrome
87.0.4280.66 (64 bit)

**Additional context**
https://github.com/EventsExpress-SoftServe/EventsExpress/issues/282

**Comment by mehalyna** [comment]
Would you be so kind and provide the corresponding requirement (user story) with a mockup and mandatory UI controls?

**Comment by ElenaMelnyk** [comment]
Please follow the link there is the corresponding requirement with a mockup and mandatory UI controls: #310

**Comment by ElenaMelnyk** [comment]
@Anastasiagumenuk9 
Pass
