### ISSUE TITLE
Bug report: The 'Title' field in the new form of the event does not meet the requirements

### ISSUE THREAD

**Issue by ElenaMelnyk** [EventsExpress-SoftServe/EventsExpress#286]
**Date Time**
12-07-2020 00:28

 **Tags**
20201207.8

**Priority**
High 

**Description**
The 'Title' field in the new form of the event can contain more than 20 characters (letters, numbers, and reserved characters).

**Pre-conditions**
1. Go to https://eventsexpress-test.azurewebsites.net/user/1a816f69-521f-4876-cd1d-08d8831eb70c
2. Llog in as an admin:
noneivaAdm@gmail.com
'password'='QWERTY123.'
3. The 'Profile' page is opened

**Steps to Reproduce**
1. Click on the  'Add' button
3. Set in the 'Title' field: '123456789012345678901234567890' 

**Expected result**
Data inputs are stopped after 20 characters 

**Actual result**
Data inputs did not stop after 20 characters 

**Screenshots**
![bug_7](https://user-images.githubusercontent.com/74773749/101412746-cba52580-38eb-11eb-8e32-9384e9e81a71.jpg)

**Environment:**
windows 10 corporate (64 bit)
Google Chrome
87.0.4280.66 (64 bit)

**Additional context**
https://github.com/EventsExpress-SoftServe/EventsExpress/issues/279

**Comment by Anastasiagumenuk9** [comment]
@ElenaMelnyk, could you provide requierements for this field?

**Comment by ElenaMelnyk** [comment]
@Anastasiagumenuk9 
Yes, of course
https://github.com/EventsExpress-SoftServe/EventsExpress/issues/279

**Comment by Anastasiagumenuk9** [comment]
Thank you, that's enough 20 characters?

**Comment by ElenaMelnyk** [comment]
@Anastasiagumenuk9 
Pass. 60 characters
