### ISSUE TITLE
Inventory units are not fully implemented in the 'Add Event' tab on the Profile page

### ISSUE THREAD

**Issue by OlenaSmereka** [EventsExpress-SoftServe/EventsExpress#312]
**Date Time**
12-08-2020 11:25

**Priority**
 Medium 
**Description**
Inventory units are not fully implemented in the form of creating a new event on the "Add Event" tab on the Profile page, and it is not possible to select any other but "kilograms".

**Pre-conditions**
1. Go to https://eventsexpress-test.azurewebsites.net/user/1a816f69-521f-4876-cd1d-08d8831eb70c
2. Sign in 
3. Click the Profile link in the left sidebar menu

**Steps to Reproduce**
1. Choose the 'Add Event' tab on the Profile page
2. Scroll to the bottom of the list and сlick the dropdown menu button next to the 'List of inventories' label
3. Click the drop-down menu button at the end of the first line 

**Expected result**
A drop-down list with different inventory units to choose from is presented

**Actual result**
The drop-down list contains only 'kilograms' units

**Screenshots**
![ивент](https://user-images.githubusercontent.com/74774487/101466336-b0690300-3949-11eb-80e3-c7dea9560c73.png)

**Environment:**
 - OS: Windows 7, 32-bit
 - Browser  Google Chrome 87.0.4280.88 (32 бит)
- Version 20201207.8

**Additional context**
Requirement #187

**Comment by mehalyna** [comment]
The list of inventories can be altered from the admin account. So it's not an issue.
