### ISSUE TITLE
Verify that an admin has a view of the number (in digits) of all registered users in the system.

### ISSUE THREAD

**Issue by vladspirin** [EventsExpress-SoftServe/EventsExpress#321]
**Date Time**
12-10-2020 13:18

**Priority**
Medium

**Type**
UI

**Description**

This test case check that every authorized user with administrator privileges has a view of the exact number (in digits) of all registered users in the system. This information contains on the 'Users' page.

**Pre-requisites**
Steps to be fulfilled before the test:

1. Move to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
2. Authorize as an admin

**Steps to Test**
Steps to test the behavior:
1. Go to the 'Users' page.
2. Check the right sidebar ('Search' field), under the radio buttons. 
3. Number (in digits) of all registered users in the system is shown after the next text: 'All registered users: '

**Expected result**

On the 'Users' page under the right sidebar ('Search' field) an authorized user with administrator privileges have a view of the exact number (in digits) of all registered users in the system. This information is shown after the text: 'All registered users: '.

**Environment:**
- OS: [e.g. Windows 10 Pro, Version 20H2, Build 19042.662]
- Browser: [e.g. Google Chrome, Version 87.0.4280.66 (Official Build) (64-bit)]
- Version [e.g. 202001204.5] 

**Additional context**

User stories: [#320 As an admin, I want to have a view of the number of registered users in the system, so that it can be used for clearer control.](https://github.com/EventsExpress-SoftServe/EventsExpress/issues/320)

**Comment by mehalyna** [comment]
Story was blocked
