### ISSUE TITLE
The authorized user with administrator privileges doesn't have a view of the number (in digits) of all registered users in the system.

### ISSUE THREAD

**Issue by vladspirin** [EventsExpress-SoftServe/EventsExpress#322]
**Date Time**
12-10-2020 15:37

**Priority**
Medium

**Environment:**
 OS: [Windows 10 Pro Version 20H2 OS Build 19042.685]
 Browser [Microsoft Edge Version 87.0.664.57 (Official build) (64-bit)]
 Reproducible: always
 Build found: (20201209.13)
 
**Pre-conditions**

1. Move to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
2. Authorize as an admin

**Steps to Reproduce**

1. Go to the 'Users' page.
2. Look at the right sidebar ('Search' field), under the radio buttons. 
3. Number (in digits) of all registered users in the system is shown after the next text: 'All registered users: '

**Expected result**

On the 'Users' page under the right sidebar ('Search' field) an authorized user with administrator privileges have a view of the exact number (in digits) of all registered users in the system. This information is shown after the text: 'All registered users: '.

**Actual result**

On the 'Users' page under the right sidebar ('Search' field) an authorized user with administrator privileges doesn't have a view of the exact number (in digits) of all registered users in the system. The text: 'All registered users: ' with information isn't shown.

**User story and test case links**

User stories: [#320 As an admin, I want to have a view of the number of registered users in the system, so that it can be used for clearer control.](https://github.com/EventsExpress-SoftServe/EventsExpress/issues/320)
Test case: [#321 Verify that an admin has a view of the number (in digits) of all registered users in the system. ](https://github.com/EventsExpress-SoftServe/EventsExpress/issues/321)

**Labels to be added** 
Type: UI 
Severity: Minor
Priority: Low

**Comment by mehalyna** [comment]
It's not a bug yet
