### ISSUE TITLE
Access token for Swagger

### ISSUE THREAD

**Issue by vladspirin** [EventsExpress-SoftServe/EventsExpress#346]

**Comment by sand0** [comment]
you can use this one for swagger (will expire in 1800000 mins from now)

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYXZjaHVrLnNhbmQwQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IjZkODc3OTBlLTE4ZjEtNDA1ZC00MmQ2LTA4ZDg1NDE0NzA2NCIsImV4cCI6MTYxMjcxNjM0N30.PWtx_tzqz-JucP7IBQ9N4Wyb519TWWZCEO8LwyVJ0sE
