### ISSUE TITLE
The modal does not close after raising or dropping the user of the event

### ISSUE THREAD

**Issue by S4ress** [EventsExpress-SoftServe/EventsExpress#348]
Priority
Low

Description
When someone wants to approve a user to owner, a modal window was not closing, but rerender for the new member.

Pre-conditions

1. Move to https://eventsexpress-test.azurewebsites.net/
2. Login into EventExpress as an owner of event

Steps to Reproduce

1. Approve someone to owner
2. Press confirm button
3. A user was successfully approved to the owner, but modal window don't close.

Expected result
The system should close modal window after raising.

Actual result
A user was successfully approved to the owner, but modal window don't close.

Screenshots

Environment:
Windows 10 Home OS Build 18363.1139
Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)

Additional context

**Comment by vladspirin** [comment]
Confirmation test: pass
Status: 'Verified'
Test case: [#363 Verify that a user approved the owner of the Event when the owner of the Event adds him/her.](https://github.com/ita-social-projects/EventsExpress/issues/363) 

![01](https://user-images.githubusercontent.com/24988700/103171324-157e8d00-4854-11eb-889d-ea1cfb1114d0.png)
