### ISSUE TITLE
Verify that the new icon of the 'Comuna' is implemented in the main navigation menu.

### ISSUE THREAD

**Issue by vladspirin** [EventsExpress-SoftServe/EventsExpress#354]
**Date Time**
12-22-2020 09:31

**Priority**
Low

**Type**
UI

**Description**
This test case for verifying that the new icon ('Comuna') shown in the mockup is implemented in the main navigation menu.

**Steps to Test**
Steps to test the behavior:
1. Go to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
2. Authorize as the user/admin
3. Move to the 'Comuna' on the main navigation menu

**Expected result**
The new icon of the 'Comuna' (shown in the mockup) is implemented in the main navigation menu.

**Test Data**
https://fontawesome.com/icons/comments?style=solid

**Screenshots**

![2020-12-22_09-19](https://user-images.githubusercontent.com/24988700/102860565-ca6d1000-4436-11eb-8ce3-6b9b27282446.png)

**Environment:**

**Additional context**
User story: [#350 As an authorized user/admin I want to have an icon of the ''Comuna' that good associated with chat for better usability.](https://github.com/ita-social-projects/EventsExpress/issues/350)

**Comment by mehalyna** [comment]
Is not a story yet
