### ISSUE TITLE
As a user, I want to be able to "Like/Dislike" the event's owner so it'll impact on his rate

### ISSUE THREAD

**Issue by ElenaMelnyk** [EventsExpress-SoftServe/EventsExpress#359]
**Date**
12.22.2020 12:33

**Priority**
Medium

**Pre-requisites**
1. The user is authorized and login into https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active

**Description**
Any authorized user who is a participant in the event must be able to "Like/Dislike" the event owner during the event active time and during the 5 days after the event end.
The "Like/Dislike" functionality:
1. Must be implemented like on the mockup and placed under the owner avatar
2. Must be enabled for the user during the event active time and during the 5 days after the event end.
3. After clicking on the Like or Dislike appears the notification "Do you want to leave a comment?" like on the mockup. After clicking on the "No" button the notification is closed. After clicking on the "Yes" button is opened the "Communa" page with the opened chat with the owner of the event. 
4. The notification "You must be a participant of the event" appears after the user clicking on the disabled "Like/Dislike" icon. The notification must be implemented and located like on the mockup. 
5. The icon of the counter like and dislike must be implemented and placed like on the mockup. The icon displayed how much the vote of the like and dislike have the user. 
6. The user can cancel exposed the "Like/Dislike" by clicking on the icon Like or Dislike during the open session. The cancel Like or Dislike is disabled next session.

**Acceptance criteria**
1. The "Like/Dislike" buttons are  implemented like on the mockup and placed under the owner avatar
2. The "Like/Dislike" buttons are enabled for the user during the event active time and during the 5 days after the event end.
3. The notification "Do you want to leave a comment?" is implemented like on the mockup and appears after clicking on the Like or Dislike.
4. The notification "You must be a participant of the event" is implemented like on the mockup and appears after the user clicking on the disabled "Like/Dislike" icon.
5. The icon of the counter like and dislike is implemented like on the mockup and displayed how much the vote of the like and dislike have the user. 
6. The user can cancel exposed the "Like/Dislike" during the open session and cancel Like or Dislike is disabled next session.

**Mockup**
![like_1](https://user-images.githubusercontent.com/74773749/102889088-ab847300-4462-11eb-8b37-acc28680f722.jpg)
![like_2](https://user-images.githubusercontent.com/74773749/102889143-c7881480-4462-11eb-9e3d-7502af8a5df8.jpg)
![like_3](https://user-images.githubusercontent.com/74773749/102889177-d79ff400-4462-11eb-8ea3-4d41ec0a0f06.jpg)
![like_4](https://user-images.githubusercontent.com/74773749/102889179-da9ae480-4462-11eb-9467-b73fcf5c7b59.jpg)
![like_5](https://user-images.githubusercontent.com/74773749/102889191-dd95d500-4462-11eb-8189-d661321f43b1.jpg)

Environment:
windows 10 corporate (64 bit)
Google Chrome
87.0.4280.66 (64 bit)

**Comment by sand0** [comment]
The "Like/Dislike" functionality is not related to the "Rate" logic.
So, as far as I can see, rates work as designed for now.

And "Like/Dislike" related requirements are not fully described, and we can't start any improvements.
