### ISSUE TITLE
As an admin, I want to have the possibility to view and create new category on the "Categories" page 

### ISSUE THREAD

**Issue by radik1999** [EventsExpress-SoftServe/EventsExpress#406]
**Date Time**
02-03-2021 11:00

**Priority**
Medium

**Pre-requisites**
   1. Go to https://eventsexpress-test.azurewebsites.net
   2. Authorize as the admin
   3. Follow to the "Categories" page

**Description**
Each admin must have the ability to view all categories on the "Categories" page.
The name of category is implemented as a list in alphabetized.
Admin must have a possibility to create a new category.
Function create new category is implemented as a `plus` button on the left corner of `Categories` tab.

**Acceptance criteria**
   1. List of all able categories is implemented.
   2.  Create new category is implemented as a "+" button.
   

![Screenshot_2](https://user-images.githubusercontent.com/78555589/116314896-637eaf80-a7b8-11eb-8359-a3d1ae465c70.png)

**Comment by IgorBloshko** [comment]
Function `Search categories` is not implemented.
