### ISSUE TITLE
As a user I want to find some template to know how to write issues.

### ISSUE THREAD

**Issue by alexlotozka** [EventsExpress-SoftServe/EventsExpress#475]

**Comment by mehalyna** [comment]
Step 1. Open the page "Issues"
Step 2. Click on "New issue"
![image](https://user-images.githubusercontent.com/39273210/114981415-a4142a00-9e96-11eb-80c6-ad67eb52cdca.png)
Step 3. Choose the type of issue
![image](https://user-images.githubusercontent.com/39273210/114981473-c017cb80-9e96-11eb-8a7f-b7c22def72d5.png)
Step 4. Just try it!
