### ISSUE TITLE
[Registration] 500 Internal Server Error appears during trying to 'Sign In' into the application

### ISSUE THREAD

**Issue by vitaliy-yavorskyi** [EventsExpress-SoftServe/EventsExpress#604]
**Date Time**
25-05-2021 13:40

**Priority**
High

**Environment:**
OS: [Windows 10]
Browser [Google Chrome]
Version [ 90.0.4430.212] 
Reproducible: always
Build found: 20210520.1
 
**Pre-conditions**
A page https://eventsexpress-test.azurewebsites.net/home/events is opened. A 'Sign in/up' pop-up is focused

**Steps to Reproduce**
1. Switch to the 'Log in' tab
2. Enter an e-mail address of an already registered user into the 'E-mail' field (e.g.eventsexpress.testuser2@gmail.com)
3. Enter a password of the already registered user into a 'Password' field (e.g. qwerty2001)
4. Right-click and select 'Перевірити' from the drop-down list --> Click on 'Network' tab
4. Click on the 'Sign in' button
5. Look at the errors with red color in the 'Network' tab and 'Console' tab

**Actual result**
The errors with red color in 'Network' tab ("550 error")  and in 'Console' tab ("SyntaxError: Unexpected end of JSON input")

**Expected result**
The user can Login into application after pressing on the 'Sign in' button
**Screenshots**
![image](https://user-images.githubusercontent.com/12746721/119483574-c9316d80-bd5d-11eb-94a8-1cf167367938.png)
![image](https://user-images.githubusercontent.com/12746721/119482950-1fea7780-bd5d-11eb-87f3-55ece5a0c23f.png)

**User story and test case links** E.g.: "User story #181"

**Labels to be added** "Bug", Priority ("pri: High"), Severity ("severity:"Critical), Type ( "Functional")

**Comment by stannydan** [comment]
You have confused field descriptions "Actual" and "Expected"

**Comment by KhrystynaYaremchuk** [comment]
> You have confused field descriptions "Actual" and "Expected"

Sorry, I corrected them
