### ISSUE TITLE
[Change avatar] A Submit button does not react when user updated an avatar

### ISSUE THREAD

**Issue by ivmariia** [EventsExpress-SoftServe/EventsExpress#618]
**Date Time**
05-28-2021 12:58

**Priority**
High 

**Environment:**
OS: Windows 10 x64
Browser Google Chrome 90.0.4430.212
Reproducible: always
Build found: 20210527.2
 
**Pre-conditions**
1. Move to https://eventsexpress-test.azurewebsites.net
2. Authorize as user /admin
3. Open the ‘Edit your profile’ page by clicking on the ‘Edit your profile’ icon.

**Steps to Reproduce**
1. Click on the ‘Change Avatar’ Expansion Panel
2. Click on 'Clear' button
3. Uppload any JPEG/PNG picture
4. Click on 'Submit' button
5. Pay attention on 'Change avatar' Expansion Panel

**Actual result**
A 'Submit' button does not react when user updated an avatar on the 'Change avatar' Expansion Panel

**Expected result**
A 'Submit' button changes a profile picture, when clicking on it after adding a picture on the 'Change avatar' Expansion Panel

**Video**

https://user-images.githubusercontent.com/84564851/119969193-ec0a8e80-bfb6-11eb-9373-6fa29cc72557.mp4

**User story and test case links** "User story #213 Test case #237 "

**Labels to be added** "Bug", Priority ("pri: High"), Severity ("severity: Minot"), Type ("Functional").

**Comment by sand0** [comment]
I guess the "crop" button must have been clicked before submitting. And this is by design.
So, probably all we should do is just disable submit while the image not cropped. 
@iuriikhrystiuk, @mehalyna, @ivmariia, @stannydan, any suggestions?

**Comment by stannydan** [comment]
I completely agree!

**Comment by ivmariia** [comment]
retested. Fixed
