### ISSUE TITLE
[Add event] 500 Internal Server Error appears after pressing on the 'Save' button 

### ISSUE THREAD

**Issue by KhrystynaYaremchuk** [EventsExpress-SoftServe/EventsExpress#656]
**Date Time**
06-11-2021 15;30

**Priority**
High

**Environment:**
OS: [Windows 10]
Browser [Google Chrome]
Version [ 90.0.4430.212]
Reproducible: always
Build found: 20210610.4
 
**Pre-conditions**
The user is login into the application. A page https://eventsexpress-test.azurewebsites.net/home/events is opened. 

**Steps to Reproduce**
1. Click on the 'Add event' button
2. To write down a title and description
3. Choose a date and country for conducting the event
4.  Add some hashtags
5. Right-click and select 'Перевірити' from the drop-down list --> Click on 'Network' tab
6. Create the event by clicking on the ‘Save’ button
7. Look at the errors with red color in the 'Network' tab and 'Console' tab

**Expected result**
The user can add an event to the " Draft" by clicking on the ‘Save’ button

**Actual result**
The errors with red color in the 'Network' tab ("550 error") and in the 'Console' tab ("Type error: Cannot convert undefined or null to object")

**Screenshots**
![image](https://user-images.githubusercontent.com/84565816/121685913-30bf1b00-cac9-11eb-8bc6-4e65a8d5d487.png)

**User story #187 "

Labels to be added "Bug", Priority ("pri: High"), Severity ("severity:"Critical), Type ( "Functional")

**Comment by stannydan** [comment]
This bug is no longer reproducible, please retest this case

**Comment by KhrystynaYaremchuk** [comment]
![image](https://user-images.githubusercontent.com/84565816/122045620-a804ef80-cde6-11eb-86d7-b8f89e45287e.png)
