### ISSUE TITLE
[Add event] 400 Bad Request Error appears after pressing on the 'Publish' button

### ISSUE THREAD

**Issue by KhrystynaYaremchuk** [EventsExpress-SoftServe/EventsExpress#657]
**Date Time**
06-11-2021 15;30

**Priority**
High

**Environment:**
OS: [Windows 10]
Browser [Google Chrome]
Version [ 90.0.4430.212]
Reproducible: always
Build found: 20210610.4
 
**Pre-conditions**
The user is login into the application. A page https://eventsexpress-test.azurewebsites.net/home/events is opened. 

**Steps to Reproduce**
1. Click on the 'Add event' button
2. To write down a title and description
3. Choose a date and country for conducting the event
4. Add some hashtags
5. Right-click and select 'Перевірити' from the drop-down list --> Click on 'Network' tab
6. Create the event by clicking on the ‘Publish’ button
7. Look at the errors with red color in the 'Network' tab and 'Console' tab

**Expected result**
The user can create an event by clicking on the ‘Publish’ button

**Actual result**
The errors with red color in the 'Network' tab ("400 error") and in the 'Console' tab ("Type error: Bad Request")

**Screenshots**
![image](https://user-images.githubusercontent.com/84565816/121688237-e4c1a580-cacb-11eb-98b0-8c6f878eb44d.png)

**User story #187 "

Labels to be added "Bug", Priority ("pri: High"), Severity ("severity:"Critical), Type ( "Functional")

**Comment by stannydan** [comment]
This is not a bug, in case of unsuccessful validation of the event, the server should return status 400
