### ISSUE TITLE
[Login] Validation message is not consistant to required, when entering incorrect email address

### ISSUE THREAD

**Issue by ivmariia** [EventsExpress-SoftServe/EventsExpress#669]
**Date Time**
06-15-2021 10:35

**Priority**
 Medium

**Environment:**
OS: Windows 10 x64 bit
Browser Chrome Version 91.0.4472.77
Reproducible always
Build found 20210614.3

**Steps to Reproduce**

1. Go to https://eventsexpress-test.azurewebsites.net/home/events
2. Click on 'Sign in/up' button in the left corner
3. Enter invalid email address into the 'Email Address' field
4. Enter password into the 'Password' field
5. Click on 'Sign in' button
6. Pay attention on the validation messages

**Actual result**
Validation message 'Incorrect email address' in red color appears under the 'Log in with facebook' and 'log in with google' buttons

**Expected result**
Validation message _**'Incorrect login or password'**_ in red color appears under the 'Log in with facebook' and 'log in with google' buttons

**Screenshots**
Actual result

![image](https://user-images.githubusercontent.com/84564851/122010746-13899580-cdc4-11eb-8b16-65549d45e173.png)

Expected result

![image](https://user-images.githubusercontent.com/84564851/122011904-45e7c280-cdc5-11eb-8575-c140675c7718.png)

**User story and test case links** E.g.: "User story #181  Test case #662 "

**Labels to be added** "Bug", Priority Medium, Severity Minor, Type UI

**Comment by Junomy** [comment]
Email validation is used for checking if email format is correct, therefore it cannot be used for whole login form
