### ISSUE TITLE
The button 'Join' is absent on the event card (authorize as admin)

### ISSUE THREAD

**Issue by mehalyna** [EventsExpress-SoftServe/EventsExpress#754]
**Date Time**
08-12-2021 17:25

**Priority**
High 

**Environment:**
 OS: Win10
 Browser Google Chrome
 Reproducible: always. 
 Build found: (e.g. tag) 20210810.1
 
**Pre-conditions**
The button 'Join' is absent on the Join Event Card

**Steps to Reproduce**
1. Go to https://eventsexpress-test.azurewebsites.net/
2. Authorize as Admin
3. Open 'Future event'

**Expected result**
The button 'Join' is placed on the Join Card

**Actual result**
The button is absent

**Screenshots**
![image](https://user-images.githubusercontent.com/39273210/129215198-c6dd2604-f297-4db8-862e-5445e0152d42.png)

**User story and test case links** E.g.: "User story #100 Test case"

**Labels to be added** "Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Junomy** [comment]
Not all users can join an event if they are owner or there are max number of participants
