### ISSUE TITLE
[Add event] Server error appears by clicking 'Publish' button

### ISSUE THREAD

**Issue by yanaHaidukova** [EventsExpress-SoftServe/EventsExpress#766]
**Date Time**
08-18-2021 19:17

**Priority**
High
**Severity**
Major
**Type**
API

**Environment:**
 OS: [Windows 10]
 Browser [Google Chrome 92.0.4515.131 ]
 Reproducible: always

 
**Pre-conditions**
1. Go to https://eventsexpress-test.azurewebsites.net/
2. Login as registered user.

**Steps to Reproduce**
1. Click 'Add event' button
2. Write down a title (e.g. 'Tree")
3. Choose 'Public' checkbox
4. Choose 'date from' current date and 'to' current date
5. Write down 'Description' (e.g. 'Treeenent")
6. Choose hashtag '#meeting'
7. Choose 'Map' radio button
8. Click 'Publish' button
**Expected result**
An event is published.

 **Actual result**
Red errors appear on the Network tab (see attached below)
**Screenshots**
![server_error_create_event 1](https://user-images.githubusercontent.com/87987196/129937257-ee0c7973-21e6-4172-828a-7e44e7719699.png)

**Comment by VovaSanduliak** [comment]
Not reproduced

**Comment by mehalyna** [comment]
Not reproducible.
