### ISSUE TITLE
[Edit profile] Cannot change 'Date of birth' by manually entered

### ISSUE THREAD

**Issue by yanaHaidukova** [EventsExpress-SoftServe/EventsExpress#783]
**Date Time**
08-26-2021 16:33

**Priority**
Medium 

**Severity**
Minor

**Type**
Functional

**Environment:**
 OS: [Windows 10]
 Browser [Microsoft Edge]
 Reproducible: always 
 
**Pre-conditions**
1. Move to https://eventsexpress-test.azurewebsites.net/
2. Log in to the system
3. Click on 'Edit your profile' button

**Steps to Reproduce**
1. Click on 'Date of birth' dropdown
2. Enter '16-05-1998' manually
3. Click on 'Submit' button

**Expected result**
'Date of birth' is changed to 16-05-1998

**Actual result**
'Date of birth' does not change and displays current date by default
**Screenshots**
![date_of_birth](https://user-images.githubusercontent.com/87987196/130972943-561db588-9e08-424d-af27-a34085920faf.png)

**User story and test case links**
User story #634 Test Case #782

**Comment by Apostall107** [comment]
Not reproducible bug.
