### ISSUE TITLE
[Event Creation] Required notification  is absent in field add image

### ISSUE THREAD

**Issue by Fevronia** [EventsExpress-SoftServe/EventsExpress#793]
**Date Time**
08-31-2021 

**Priority**
 Medium 

**Environment:**
 OS: Windows 10
 Browser chrome
 Reproducible: sometimes

**Description**
Required notification is absent in field add image when you published event with out image
 
 
**Pre-conditions**
The user is authorized and login into https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active

**Steps to Reproduce**
1. Go to Home page
2. Click on add event
3. DO NOT ADD IMAGE
4. Fill all the field with correct data
5. Press publish button

**Expected result**
Expected notification that image is required

**Actual result**
Notification is absent
**Screenshots**

https://user-images.githubusercontent.com/26015335/131504617-9f9a633b-08b6-4830-9aaf-3a0c76d270c1.mp4

story #279

**Labels to be added** "Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by mehalyna** [comment]
not an issue
