### ISSUE TITLE
[Landing Page][Block3] The date format of the upcoming event does not match the mock-up

### ISSUE THREAD

**Issue by YatskivNataliya** [EventsExpress-SoftServe/EventsExpress#886]
**Date Time**
10-12-2021 09:40

**Priority**
 Low

**Environment:**
OS: Win 10
Browser Google Chrome 92.0.4515.159
Reproducible: always
Build found: 20210906.18
 
**Pre-conditions**

**Steps to Reproduce**
1. Open the https://eventsexpress-test.azurewebsites.net/landing.
2. Scroll to Block 3 "Upcoming events" of the landing page.
3. Check date format

**Expected result**
The date format matches the mock-up ( SUN, AUG 1@ 6:00 PM GMT+3).

**Actual result**
The date format of the upcoming event (2021-04-30T00:00:00) does not match the mock-up
**Screenshots**
![зображення](https://user-images.githubusercontent.com/89734792/136906948-fa92adee-7343-4a87-8551-25adae029035.png)
![зображення](https://user-images.githubusercontent.com/89734792/136910324-3540cc2e-7c3f-4679-b237-d6e54ba51e06.png)

**Postconditions**

**User story and test case links**  "User story #713 Test case # 881"

**Labels to be added** "Bug", Priority ("pri: low "), Severity ("severity: low"), Type ("UI").

**Comment by RaccoonBoryvitter** [comment]
[Block 3] is missing because there were no events created in our system. It means that someone must create a new event so that [Block 3] should be displayed. As an improvement, I can offer to create some placeholder if there are no events.

**Comment by YatskivNataliya** [comment]
Looks like this comment relates to another bug #887  
When I login as Admin I see upcoming events in Block 3, so there are some events in the system
